version: '3.8'
services:
  client:
    image: skytvvo/immensus-client
    env_file: .env
    ports:
      - '4200:4200'
  authorization-service:
    image: skytvvo/immensus-authorization-service
    env_file:
      - .env
    ports:
      - '4400:4400'
  gateway-service:
    image: skytvvo/immensus-gateway-service
    env_file:
      - .env
    ports:
      - '4401:4401'
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123
