version: '3.8'
services:
  client:
    image: skytvvo/immensus-client
    env_file: .env
    ports:
      - '4200:4200'
  authorization-service:
    image: skytvvo/immensus-authorization-service
    env_file:
      - .env
    ports:
      - '4401:4401'
