name: Continues Delivery
on: push
jobs:
  linting-client:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Node.JS Installation
        uses: actions/setup-node@v3
      - name: Caching
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ci-caching-${{ hashFiles('**/package-lock.json') }}
      - name: Usage of NX
        uses: nrwl/nx-set-shas@v3
      - name: Packages installation
        run: npm ci
      - name: Linting
        run: npx nx affected --target=lint --parallel=3
      - name: Testing
        run: npx nx affected --target=test --parallel=3
      - name: Building storybook
        run: npx nx affected --target=storybook-build --parallel=3
      - name: Building client
        run: npx nx affected --target=build --parallel =3
  linting-server:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Node.JS Installation
        uses: actions/setup-node@v3
      - name: Caching
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ci-caching-${{ hashFiles('**/package-lock.json') }}
      - name: Packages installation
        run: npm ci
      - name: Lint server side
        run: npm run server:lint
  testing-client:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Node.JS Installation
        uses: actions/setup-node@v3
      - name: Caching
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ci-caching-${{ hashFiles('**/package-lock.json') }}
      - name: Packages installation
        run: npm ci
      - name: Lint server side
        run: npm run client:test
  testing-server:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Node.JS Installation
        uses: actions/setup-node@v3
      - name: Caching
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ci-caching-${{ hashFiles('**/package-lock.json') }}
      - name: Packages installation
        run: npm ci
      - name: Lint server side
        run: npm run server:test
